baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My First Website!'
[deployment]

[[deployment.targets]]
# An arbitrary name for this target.
name = "production"

# URL specifies the Go Cloud Development Kit URL to deploy to. Examples:
URL = "gs://ipug29-my-first-bucket"
